package ViewUIs;

import Controllers.SingleCourseController;
import Models.Course;

import javax.swing.*;
import java.awt.*;

public class SingleCourseUI extends JFrame {

    private SingleCourseController controller;
    private int selectedRow;
    private Course currentCourse;
    private JPanel mainPanel;
    private JPanel labelsPanel;
    private JPanel detailPanel;
    private JLabel nameLabel;
    private JLabel courseStatusLabel;
    private JLabel summerAvailableLabel;
    private JLabel numCreditsLabel;
    private JLabel courseCodeLabel;
    private JPanel buttonPanel;
    public JButton cancelEditButton;
    public JButton editButton;
    public JButton saveButton;
    public JButton exitButton;
    private JPanel inputPanel;
    public JTextField newCourseTextField;

    public SingleCourseUI(SingleCourseController singleCourseController, int selectedRow) {
        this.controller = singleCourseController;
        this.selectedRow = selectedRow;
        this.currentCourse = controller.getCourse(selectedRow);
        setContentPane(mainPanel);

//        this.courses = controller.getListOfCourses();
//        this.course = courses.get(currentCourseNumber);
//        this.studentCourses = controller.getStudentCoursesList();
        parseCourse();
//        parseStudentCourseList();
    }


    public void parseCourse() {
        nameLabel.setText(currentCourse.getName());
        courseCodeLabel.setText(currentCourse.getCourseCode());
        numCreditsLabel.setText(currentCourse.getNumCredits() +"");
        summerAvailableLabel.setText((currentCourse.getSummer() ? "Yes" : "No"));
        courseStatusLabel.setText(currentCourse.getCourseStatus().toString());
    }




    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        labelsPanel = new JPanel();
        labelsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 5, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(labelsPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        nameLabel = new JLabel();
        nameLabel.setText("Name");
        labelsPanel.add(nameLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        courseStatusLabel = new JLabel();
        courseStatusLabel.setText("Course Status");
        labelsPanel.add(courseStatusLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        summerAvailableLabel = new JLabel();
        summerAvailableLabel.setText("Summer Available");
        labelsPanel.add(summerAvailableLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        courseCodeLabel = new JLabel();
        courseCodeLabel.setText("Course Code");
        labelsPanel.add(courseCodeLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        numCreditsLabel = new JLabel();
        numCreditsLabel.setText("# Credits");
        labelsPanel.add(numCreditsLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        detailPanel = new JPanel();
        detailPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(detailPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
